export default [
  'LARGE WALK-IN VOLUME FOR MANUAL PROCESS',
  'LARGE APE VOLUME FOR MANUAL PROCESS',
  'DATA TRACKING OF PATIENT & PATIENT SERVICES',
  'DATA TRACKING OF FINANCE OPERATIONS',
  'DATA TRACKING OF LOGISTICS & INVENTORY OPERATIONS',
  'DATA TRACKING OF CLIENTS MANAGEMENT',
  'DATA TRACKING OF MULTI-BRANCH OPERATIONS',
  'OTHERS'
]
