export default [
  'NO BUDGET',
  'PRICING TOO EXPENSIVE',
  'SATISFIED WITH CURRENT SYSTEM',
  'LACKING FEATURES',
  'DOES NOT LIKE DASHLABS',
  'SMALL VOLUME',
  'BUDGET IS FOR IN-HOUSE LIS',
  'UNQUALIFIED',
  'OTHERS'
]
