export default [
  'LEAD RESEARCH',
  'SALES CADENCE',
  'INITIAL ENGAGEMENT',
  'PRE-PRESENTATION PROFILING',
  'PRESENTATION',
  'PROPOSAL SENDING',
  'CLOSE NURTURING',
  'NEGOTIATION/FINALIZATION',
  'FOLLOW-UP'
]
